server:
  port: 8090

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          # 218
          url: jdbc:mysql://192.168.50.218:3306/legal_aid?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
          password: 123456
          username: root
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis-plus
mybatis-plus:
  # xml 扫描
  mapper-locations: classpath*:com/aegis/modules/*/*/dao/mapper/*Mapper.xml

#白名单接口
security:
  white-list: /demo/**